# -*- coding: utf-8 -*-
"""my generative poster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FQt1C1bkkftxegHt1hGiWz8_K1TJ8AQv
"""

# Week 4 -Interactive Generative Poster
# Concepts: sliders, interactivity, parameter control
# Method: Coding with Prompt approach

import random, math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import hsv_to_rgb
import ipywidgets as widgets
from ipywidgets import interact

# Blob shape
def blob(center=(0.5, 0.5), r=0.3, points=200, wobble=0.15):
  angles = np.linspace(0, 2*math.pi, points, endpoint=False)
  radii  = r * (1 + wobble*(np.random.rand(points)-0.5))
  x = center[0] + radii * np.cos(angles)
  y = center[1] + radii * np.sin(angles)
  return x, y

# Simple palette generator (HSV pastel/vivid/mono)
def make_palette(k=6, mode="pastel", base_h=0.60):
  cols = []
  for _ in range(k):
    if mode == "pastel":
      h = random.random(); s = random.uniform(0.15,0.35); v = random.uniform(0.9,1.0)
    elif mode == "vivid":
      h = random.random(); s = random.uniform(0.8,1.0);  v = random.uniform(0.8,1.0)
    elif mode == "mono":
      h = base_h;         s = random.uniform(0.2,0.6);   v = random.uniform(0.5,1.0)
    else: # random
      h = random.random(); s = random.uniform(0.3,1.0); v = random.uniform(0.5,1.0)
    cols.append(tuple(hsv_to_rgb([h,s,v])))
  return cols

# Main drawing function
def draw_poster(n_layers=8, wobble=0.15, palette_mode="pastel", seed=0):
    random.seed(seed); np.random.seed(seed)
    fig, ax = plt.subplots(figsize=(6,8))
    ax.axis('off')
    ax.set_facecolor((0.97,0.97,0.97))

    palette = make_palette(6, mode=palette_mode)
    for _ in range(n_layers):
      cx, cy = random.random(), random.random()
      rr = random.uniform(0.15, 0.45)
      x, y = blob((cx,cy), r=rr, wobble=wobble)
      color = random.choice(palette)
      alpha = random.uniform(0.3, 0.6)
      ax.fill(x, y, color=color, alpha=alpha, edgecolor=(0,0,0,0))

    ax.text(0.05, 0.95, f"Interactive Poster • {palette_mode}",
            transform=ax.transAxes, fontsize=12, weight="bold")
    plt.show()

# Interactive UI with sliders
interact(
    draw_poster,
    n_layers=widgets.IntSlider(min=3,max=20,step=1,value=8, description="Layers"),
    wobble=widgets.FloatSlider(min=0.01,max=0.3,step=0.01,value=0.15, description="Wobble"),
    palette_mode=widgets.Dropdown(options=["pastel","vivid","mono","random"], value="pastel"),seed=widgets.IntSlider(min=0,max=9999,step=1,value=0, description="Seed")
);